// 75 Hard Challenge Constants

export const TOTAL_DAYS = 75;
export const MAX_MISSED_DAILY = 1; // Miss 2+ = reset

export const DAILY_HABITS = [
    { id: 'pray_morning', label: 'Pray after waking up', emoji: '🙏', category: 'spiritual' },
    { id: 'pray_night', label: 'Pray before sleep', emoji: '🌙', category: 'spiritual' },
    { id: 'cat_prep', label: 'CAT preparation', emoji: '📚', category: 'study' },
    { id: 'marketing_prep', label: 'Marketing preparation', emoji: '📊', category: 'study' },
    { id: 'english_practice', label: 'English speaking practice', emoji: '🗣️', category: 'growth' },
    { id: 'instagram_reel', label: 'Post 1 Instagram reel', emoji: '📱', category: 'content' },
    { id: 'walk_steps', label: 'Walk 10,000 steps', emoji: '🚶‍♀️', category: 'fitness' },
    { id: 'no_fried', label: 'No fried food', emoji: '🚫', category: 'diet' },
    { id: 'no_sugar', label: 'No sugar', emoji: '🍬', category: 'diet' },
    { id: 'no_outside_food', label: 'No outside food', emoji: '🏠', category: 'diet' },
    { id: 'water_3l', label: 'Drink 3 liters of water', emoji: '💧', category: 'health' },
    { id: 'exercise_daily', label: 'Exercise', emoji: '💪', category: 'fitness' },
    { id: 'no_screen_morning', label: 'No screen 30 mins after waking', emoji: '📵', category: 'wellness' },
    { id: 'read_5pages', label: 'Read 5 pages', emoji: '📖', category: 'growth' },
    { id: 'post_twitter', label: 'Post on Twitter', emoji: '🐦', category: 'content' },
];

export const WEEKLY_HABITS = [
    { id: 'cook_meal', label: 'Cook 1 full meal', emoji: '👩‍🍳', category: 'lifestyle' },
    { id: 'youtube_video', label: 'Upload 1 YouTube video', emoji: '🎬', category: 'content' },
];

export const MOTIVATIONAL_QUOTES = [
    { quote: "She believed she could, so she did.", author: "R.S. Grey" },
    { quote: "Progress, not perfection.", author: "Unknown" },
    { quote: "You are one decision away from a totally different life.", author: "Mark Batterson" },
    { quote: "Small daily improvements are the key to staggering long-term results.", author: "Unknown" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
    { quote: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
    { quote: "Don't wish for it, work for it.", author: "Unknown" },
    { quote: "Be stronger than your excuses.", author: "Unknown" },
    { quote: "It's not about being the best. It's about being better than you were yesterday.", author: "Unknown" },
    { quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
    { quote: "A flower does not think of competing with the flower next to it. It just blooms.", author: "Zen Shin" },
    { quote: "Stars can't shine without darkness.", author: "Unknown" },
    { quote: "You didn't come this far to only come this far.", author: "Unknown" },
    { quote: "Glow up in silence. Let them wonder.", author: "Unknown" },
    { quote: "Trust the timing of your life.", author: "Unknown" },
    { quote: "Create a life you can't wait to wake up to.", author: "Unknown" },
    { quote: "Make yourself proud.", author: "Unknown" },
    { quote: "Difficult roads lead to beautiful destinations.", author: "Unknown" },
    { quote: "You are enough. You have enough. You do enough.", author: "Unknown" },
    { quote: "Be so good they can't ignore you.", author: "Steve Martin" },
    { quote: "The only bad workout is the one that didn't happen.", author: "Unknown" },
    { quote: "Inhale confidence, exhale doubt.", author: "Unknown" },
    { quote: "You are your only limit.", author: "Unknown" },
    { quote: "Self-care is not selfish.", author: "Unknown" },
    { quote: "Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.", author: "Unknown" },
    { quote: "The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has ever been before.", author: "Albert Einstein (adapted)" },
    { quote: "Elegance is when the inside is as beautiful as the outside.", author: "Coco Chanel" },
    { quote: "Life is tough, darling, but so are you.", author: "Stephanie Bennett-Henry" },
    { quote: "When nothing goes right, go left.", author: "Unknown" },
    { quote: "A little progress each day adds up to big results.", author: "Satya Nani" },
    { quote: "She remembered who she was and the game changed.", author: "Lalah Delia" },
    { quote: "The best project you'll ever work on is you.", author: "Unknown" },
    { quote: "Don't stop until you're proud.", author: "Unknown" },
    { quote: "You were born to be real, not to be perfect.", author: "Ralph Marston" },
    { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { quote: "Your vibe attracts your tribe.", author: "Unknown" },
    { quote: "The comeback is always stronger than the setback.", author: "Unknown" },
    { quote: "Believe in your inner Beyoncé.", author: "Unknown" },
    { quote: "Hustle in silence, let success make the noise.", author: "Unknown" },
    { quote: "Today is a good day to have a good day.", author: "Unknown" },
    { quote: "Be fearless in the pursuit of what sets your soul on fire.", author: "Jennifer Lee" },
    { quote: "Good things come to those who hustle.", author: "Unknown" },
    { quote: "Note to self: I am going to make you so proud.", author: "Unknown" },
    { quote: "Consistency is key. Keep going.", author: "Unknown" },
    { quote: "Turn your can'ts into cans and your dreams into plans.", author: "Unknown" },
    { quote: "She is clothed in strength and dignity, and she laughs without fear of the future.", author: "Proverbs 31:25" },
    { quote: "You glow differently when you're doing the right thing.", author: "Unknown" },
    { quote: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Invest in yourself. It pays the best interest.", author: "Benjamin Franklin" },
    { quote: "In a world where you can be anything, be kind to yourself.", author: "Unknown" },
    { quote: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
    { quote: "You are what you do, not what you say you'll do.", author: "Carl Jung" },
    { quote: "A year from now, you'll wish you had started today.", author: "Karen Lamb" },
    { quote: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
    { quote: "Own your morning. Elevate your life.", author: "Robin Sharma" },
    { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { quote: "You're allowed to be both a masterpiece and a work in progress.", author: "Sophia Bush" },
    { quote: "The way you treat yourself sets the standard for others.", author: "Sonya Friedman" },
    { quote: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
    { quote: "What we think, we become.", author: "Buddha" },
    { quote: "Let your faith be bigger than your fear.", author: "Unknown" },
    { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { quote: "Strive for progress, not perfection.", author: "Unknown" },
    { quote: "You can and you will.", author: "Unknown" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Be the energy you want to attract.", author: "Unknown" },
    { quote: "Bloom where you're planted.", author: "Unknown" },
    { quote: "Stay patient and trust your journey.", author: "Unknown" },
    { quote: "Darling, stop comparing. Your journey is unique.", author: "Unknown" },
    { quote: "Beauty begins the moment you decide to be yourself.", author: "Coco Chanel" },
    { quote: "Dream without fear. Love without limits.", author: "Unknown" },
    { quote: "You are too beautiful a soul to dim your shine.", author: "Unknown" },
    { quote: "Chase your wildest dreams.", author: "Unknown" },
    { quote: "Rest if you must, but don't you quit.", author: "Edgar A. Guest" },
];

export const CATEGORY_COLORS = {
    spiritual: '#e8b4f8',
    study: '#b4d4f8',
    growth: '#b4f8d4',
    content: '#f8d4b4',
    fitness: '#f8b4b4',
    diet: '#f8e4b4',
    health: '#b4e8f8',
    wellness: '#d4b4f8',
    lifestyle: '#f8b4d4',
};
